apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $CLUSTER_NAME
  region: ap-northeast-2
  version: "1.32"
  tags:
    Environment: "Production"
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: metrics-server
    version: latest
iam:
  withOIDC: true
vpc:
  id:
  subnets:
    private:
      was-a:
        id: $PRIVATE_SUBNET_1_ID
      was-b:
        id: $PRIVATE_SUBNET_2_ID
      was-c:
        id: $PRIVATE_SUBNET_3_ID
  clusterEndpoints:
    publicAccess: false
    privateAccess: true

managedNodeGroups:
  - name: was
    labels:
      area: web
    instanceType: t3.small
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    privateNetworking: true
    volumeSize: 30
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
    tags:
      eksctl.io/nodegroup-name: "was"
    subnets:
      - was-a:
      - was-b:
      - was-c:
