AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Policy for Teleport DynamoDB Access

Resources:
  TeleportDynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Grants Teleport access to DynamoDB backend tables
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "ClusterStateStorage"
            Effect: "Allow"
            Action:
              - "dynamodb:BatchWriteItem"
              - "dynamodb:UpdateTimeToLive"
              - "dynamodb:PutItem"
              - "dynamodb:DeleteItem"
              - "dynamodb:Scan"
              - "dynamodb:Query"
              - "dynamodb:DescribeStream"
              - "dynamodb:UpdateItem"
              - "dynamodb:DescribeTimeToLive"
              - "dynamodb:CreateTable"
              - "dynamodb:DescribeTable"
              - "dynamodb:GetShardIterator"
              - "dynamodb:GetItem"
              - "dynamodb:ConditionCheckItem"
              - "dynamodb:UpdateTable"
              - "dynamodb:GetRecords"
              - "dynamodb:UpdateContinuousBackups"
            Resource:
              - "arn:aws:dynamodb:ap-northeast-2:$ACCOUNT_ID:table/teleport-helm-backend"
              - "arn:aws:dynamodb:ap-northeast-2:$ACCOUNT_ID:table/teleport-helm-backend/stream/*"

          - Sid: "ClusterEventsStorage"
            Effect: "Allow"
            Action:
              - "dynamodb:CreateTable"
              - "dynamodb:BatchWriteItem"
              - "dynamodb:UpdateTimeToLive"
              - "dynamodb:PutItem"
              - "dynamodb:DescribeTable"
              - "dynamodb:DeleteItem"
              - "dynamodb:GetItem"
              - "dynamodb:Scan"
              - "dynamodb:Query"
              - "dynamodb:UpdateItem"
              - "dynamodb:DescribeTimeToLive"
              - "dynamodb:UpdateTable"
              - "dynamodb:UpdateContinuousBackups"
            Resource:
              - "arn:aws:dynamodb:ap-northeast-2:$ACCOUNT_ID:table/teleport-helm-event"
              - "arn:aws:dynamodb:ap-northeast-2:$ACCOUNT_ID:table/teleport-helm-event/index/*"

Outputs:
  PolicyARN:
    Description: ARN of the created IAM policy
    Value: !Ref TeleportDynamoDBPolicy
