apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teleport-team
subjects:
  - kind: Group
    # Bind the group "viewers" to the kubernetes_groups assigned in the "kube-access" role
    name: team
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  # "view" is a default ClusterRole that grants read-only access to resources
  # See: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
  name: edit
  apiGroup: rbac.authorization.k8s.io